name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: scp
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./build/libs/lwes-0.0.1-SNAPSHOT.jar
        remote: server/lwes-0.0.1-SNAPSHOT.jar
        host: ${{ secrets.IP }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.ID_RSA }}
        port: ${{ secrets.PORT }}
    - name: start_server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ID_RSA }}
        port: ${{ secrets.PORT }}
        script: |
          mkdir test