name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Set SSH Environment
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: scp
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./build/libs/lwes-0.0.1-SNAPSHOT.jar
        remote: scp/server/lwes-0.0.1-SNAPSHOT.jar
        host: ${{ secrets.IP }}
        username: ${{ secrets.USERNAME }}
        privateKey: ~/.ssh/id_rsa
        port: ${{ secrets.PORT }}
